Repository macrocosm-os/prompting, pull requests merged in 2024-02, with the labels that each got.

#41 Features/reference during dendrite
  prompting/base/validator.py
  prompting/conversation.py
  prompting/forward.py
  prompting/rewards/pipeline.py
  prompting/tasks/debugging.py
  tests/test_forward.py
Labels: v1.0.3

#92 Features/decay scores
  prompting/base/validator.py
  prompting/utils/config.py
Labels: v1.0.3

#109 Features/context
  .github/workflows/python-package.yml
  prompting/base/validator.py
  prompting/conversation.py
  prompting/rewards/__init__.py
  prompting/rewards/pipeline.py
  prompting/tasks/__init__.py
  prompting/tasks/date_qa.py
  prompting/tasks/debugging.py
  prompting/tasks/math.py
  prompting/tasks/qa.py
  prompting/tasks/summarization.py
  prompting/tasks/task.py
  prompting/tools/__init__.py
  prompting/tools/dataset.py
  prompting/tools/datasets/__init__.py
  prompting/tools/datasets/base.py
  prompting/tools/datasets/code.py
  prompting/tools/datasets/context.py
  prompting/tools/datasets/math.py
  prompting/tools/datasets/mock.py
  prompting/tools/datasets/wiki.py
  prompting/tools/selector.py
  prompting/utils/exceptions.py
  requirements.txt
  tests/fixtures/dataset.py
  tests/fixtures/task.py
  tests/test_dataset.py
  tests/test_tasks.py
Labels: v1.1.0

#108 Logging/neuron info
  neurons/miner.py
  neurons/miners/openai/miner.py
  neurons/miners/test/echo.py
  neurons/miners/test/mock.py
  neurons/miners/test/phrase.py
  neurons/miners/wiki_agent/miner.py
  neurons/miners/zephyr/miner.py
  neurons/validator.py
Labels: v1.1.0

#105 Update README.md
  README.md
Labels: v1.1.0

#120 Improved miner logging
  neurons/miner.py
  neurons/miners/openai/miner.py
  neurons/miners/test/echo.py
  neurons/miners/test/mock.py
  neurons/miners/test/phrase.py
  neurons/miners/wiki_agent/miner.py
  neurons/miners/zephyr/miner.py
Labels: v1.1.1

#115 114 reduce penalty weight
  prompting/rewards/pipeline.py
  prompting/tasks/qa.py
  prompting/tasks/summarization.py
  tests/test_tasks.py
Labels: v1.1.1

#124 Hotfix/date qa redirect
  prompting/tools/datasets/base.py
  prompting/tools/datasets/wiki.py
Labels: v1.1.1
