Repository macrocosm-os/prompting, pull requests merged in 2024-06, with the labels that each got.

#243 Fix repeated tasks on CUDA OOM
  prompting/base/validator.py
  prompting/forward.py
Labels: 2.3.2

#235 Fix Llama3 miner 4bit flag, update requirements, etc
  README.md
  prompting/llms/hf.py
  prompting/utils/config.py
  requirements.txt
Labels: 2.3.2

#244 Features/discourage base miners
  README.md
Labels: 2.3.2

#246 Bittensor 7.0.0, vllm 0.4.2 upgrade
  prompting/base/validator.py
  prompting/forward.py
  requirements.txt
Labels: 2.3.2

#249 Increase miner sampling for each step
  prompting/forward.py
  prompting/utils/config.py
Labels: 2.4.0

#234 Features/streaming penalty
  prompting/__init__.py
  prompting/dendrite.py
  prompting/forward.py
  prompting/llms/base_llm.py
  prompting/llms/vllm_llm.py
  prompting/mock.py
  prompting/protocol.py
  prompting/rewards/__init__.py
  prompting/rewards/code_diff.py
  prompting/rewards/date.py
  prompting/rewards/float_diff.py
  prompting/rewards/ordinal.py
  prompting/rewards/pipeline.py
  prompting/rewards/relevance.py
  prompting/rewards/reward.py
  prompting/rewards/rouge.py
  prompting/rewards/streaming.py
  prompting/tasks/task.py
  tests/test_mock.py
  tests/test_reward.py
Labels: 2.4.0

#250 v2.4.0
  README.md
  min_compute.yml
  prompting/__init__.py
  prompting/dendrite.py
  prompting/forward.py
  prompting/llms/base_llm.py
  prompting/llms/hf.py
  prompting/llms/vllm_llm.py
  prompting/mock.py
  prompting/protocol.py
  prompting/rewards/__init__.py
  prompting/rewards/code_diff.py
  prompting/rewards/date.py
  prompting/rewards/float_diff.py
  prompting/rewards/ordinal.py
  prompting/rewards/pipeline.py
  prompting/rewards/relevance.py
  prompting/rewards/reward.py
  prompting/rewards/rouge.py
  prompting/rewards/streaming.py
  prompting/tasks/task.py
  prompting/utils/config.py
  prompting/utils/logging.py
  requirements.txt
  tests/test_mock.py
  tests/test_reward.py
Labels: 2.4.0

#261 Features/bittensor upgrade
  .gitignore
  prompting/__init__.py
  requirements.txt
Labels: 2.5.0

#263 Sn1 5 push pr to reduce tasks for multi turn qa
  prompting/forward.py
  tests/test_forward.py
Labels: 2.5.0

#264 Features/improve multi turn qa
  prompting/tasks/qa.py
Labels: 2.5.0

#267 Sn1 12 multi turn task integration
  prompting/tasks/qa.py
Labels: 2.5.0

#277 Reduce timeout to 15 seconds
  prompting/utils/config.py
Labels: 2.5.1

#270 feat: Add PM2 installation commands to install.sh for streamlined setup
  install.sh
Labels: 2.5.1

#274 update logging to use python rather than loguru
  prompting/utils/config.py
  prompting/utils/logging.py
Labels: 2.5.1

#280 Change event logging
  prompting/__init__.py
  prompting/utils/logging.py
  requirements.txt
Labels: 2.5.1

#279 Add PM2 installation commands to install.sh
  install.sh
Labels: 2.5.1
